import { useGLTF } from "@react-three/drei";
import { Models } from "../types";


export function Alastor(props) {
  const { nodes, materials } : {
    nodes: any,
    materials: any
  } = useGLTF(Models.Alastor);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_7.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_8.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_9.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_11.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_12.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_13.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_14.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_15.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_16.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_17.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_18.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_19.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_20.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_21.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_22.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_23.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_24.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_25.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_26.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_27.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_28.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_29.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_30.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_31.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_32.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_33.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_34.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_35.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_36.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_37.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_38.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_39.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_40.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_41.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_42.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_43.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_44.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_45.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_46.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_47.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_48.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_49.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_50.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_51.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_52.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_53.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_54.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_55.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_56.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_57.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_58.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_59.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_60.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_61.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_62.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_63.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_64.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_65.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_66.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_67.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_68.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_69.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_70.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_71.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_72.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_73.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_74.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_75.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_76.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_77.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_78.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_79.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_80.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_81.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_82.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_83.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_84.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_85.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_86.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_87.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_88.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_89.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_90.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_91.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_92.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_93.geometry}
            material={materials.DefaultMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(Models.Alastor)
